name: Branch

on: [push, pull_request]

jobs:

  test:
    name: Test
    
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: PowerShell script
    # uses: Amadevus/pwsh-script@1f1751bbf3d1a92127bfc6c32403283625880cbf 
        uses: Amadevus/pwsh-script@v2.0.1
        with:
         poweshell-version: 2.0.1
      - name: setup job
        run: .\example.ps1
