name: Directory creation
on: [push, pull_request]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    - name: Creating new directory in local
      run: .\sample.ps1                
      shell: powershell
