name: Branch

on: [push, pull_request]

jobs:

  test:
    name: Test
    
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v1
      - name: PowerShell script
        run: .\example.ps1
        shell: powershell
